image: brianegan/flutter:v7

stages:
  - test
  - deploy

unit_test:
  stage: test
  script:
    - flutter test --coverage
    - genhtml coverage/lcov.info --output=coverage
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - unit_test
  script:
    - mkdir public
    - mv coverage/ public/coverage/
  artifacts:
    paths:
      - public
  only:
    - master