language: dart

addons:
  apt:
    packages:
      - lib32stdc++6

install:
  - git clone https://github.com/flutter/flutter.git -b stable
  - ./flutter/bin/flutter doctor

script:
  - ./flutter/bin/cache/dart-sdk/bin/dartfmt -n --set-exit-if-changed ./lib ./test ./example ./example_async_and_test || travis_terminate 1
  - ./flutter/bin/flutter test --coverage --coverage-path=lcov.info

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.pub-cache
